N + 1 prob milestone.
Nowembabazi/BLOG-APP pull request #8
Opened 2023-02-21 09:21 UTC by Nowembabazi

#In this milestone i achieved the following;
-Write integration tests with Capybara gem.
-Secure app from n+1 problems.
Below are screenshots.
Before-
![217188834-a56e0faa-27df-4d52-9c6b-efdcc138a415](https://user-images.githubusercontent.com/109085430/220302537-2ebaf249-0659-4f4b-86f6-23c3a3d6e30b.jpg)

After-
![217188867-580f7200-fb86-4bea-9007-018be350b6ed](https://user-images.githubusercontent.com/109085430/220302670-993e2ade-2def-460b-8c3c-0ef7f6db57f6.jpg)

2023-02-21 10:14 UTC, KayLemba requested changes
Hi @Nowembabazi    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-21 10:14 UTC, KayLemba commented on spec/views/posts/index.html.erb_spec.rb
> +end
While you did a good job working on the project requirements whenever I run your tests there seems to be an error please kindly fix this issue.
![Screenshot 2023-02-21 at 12 06 36 PM](https://user-images.githubusercontent.com/79506105/220314885-c3fdbc2e-8476-4949-80e4-bf9be0d70866.png)

2023-02-21 17:02 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @Nowembabazi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] You used `sqlite3` for creating the database, Please use `postgres` instead to configure your database. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-02-22 15:01 UTC, 1GORDON requested changes
##
## Hi @Nowembabazi ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 15:01 UTC, 1GORDON commented on Gemfile
> +gem 'pg', '~> 1.1'
Great job @Nowembabazi 🤝

- [ ] Just like the previous reviewer suggested, I keep getting this error whenever I try to run the tests.
![error](https://user-images.githubusercontent.com/63917725/220661476-c2e93f15-f78c-4b35-bbf6-088da64628a8.PNG)

2023-02-23 07:11 UTC, Davidosky007 requested changes
Hi @Nowembabazi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* All tests passed ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 07:11 UTC, Davidosky007 commented on spec/features/post_index_spec.rb
> +      @post1 = Post.create(
* As the previous CR pointed out I still see some failing tests, Kindly fix them 🙏 
![image](https://user-images.githubusercontent.com/52497246/220840558-7ca26be7-4e33-4ba8-bff6-22cd890c61cb.png)

2023-02-23 07:16 UTC, Davidosky007 approved these changes
Hi @Nowembabazi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* All tests passed ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 07:25 UTC, merged